spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    username: dream
#    password: ZAQxsw!@#
#    url: jdbc:mysql://118.89.191.100/sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    url: jdbc:mysql://localhost/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
